apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#commonLabels:
#  tenant: example-app
#resources:
#- groups
# - argocd

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: tenant
    valuesInline:
      global:
        tenant: example-app
