apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  # add team to editors rolebinding
  - path: patch-rolebinding-append-team.yml
    target:
      kind: RoleBinding
      name: editors

  # remove team from viewers rolebinding
  - path: patch-rolebinding-remove-subject.yml
    target:
      kind: RoleBinding
      name: viewers
