apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  tenant: demo-gitops-cicd

resources:
  - namespaces

components:
  - ../../components/tenant-groups


replacements:
  # prefix the tenant name to the rolebindings' group names
  - source:
      kind: Namespace
      fieldPath: metadata.labels.tenant
      name: dev
    targets:
      - select:
          kind: RoleBinding
        fieldPaths:
          - subjects.0.name
        options:
          delimiter: '-'
          index: -1

  # prefix the tenant name to the namespaces argocd label
  - source:
      kind: Namespace
      fieldPath: metadata.labels.tenant
      name: dev
    targets:
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.labels.[argocd.argoproj.io/managed-by]
        options:
          delimiter: '-'
          index: -1
