apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  tenant: demo-gitops-cicd

resources:
  - groups
  - namespaces

replacements:
  # source from the tenant label
  - source:
      kind: Namespace
      name: dev
      fieldPath: metadata.labels.tenant
    targets:

      # prefix rolebinding group names
      - select:
          kind: RoleBinding
        fieldPaths:
          - subjects.[name=admins].name
          - subjects.[name=team].name
        options:
          delimiter: '-'
          index: -1

      # prefix rolebinding for serviceaccountnamespaces
      - select:
          kind: RoleBinding
        fieldPaths:
          - subjects.[namespace=gitops].namespace
        options:
          delimiter: '-'
          index: -1

      # prefix managed-by label for namespaces
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.labels.[argocd.argoproj.io/managed-by]
        options:
          delimiter: '-'
          index: -1
