apiVersion: v1
kind: Secret
metadata:
  name: repo-greeting-ui
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: examples-greeting-ui
  url: https://github.com/stocky37/ex-greeting-ui-k8s.git
  type: git
