apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "groups.team.name" . }}
  namespace: {{ include "namespace.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.restricted | ternary "edit" "admin" }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ include "groups.team.name" . }}
