apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-app-prod
commonLabels:
  environment: prod

resources:
- ../../base

# remove developers from production edit group
patches:
- path: patch-rbac.yml
  target:
    kind: RoleBinding
    name: example-app-editors
