apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-gitops-cicd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: demo-gitops-cicd-cicd
    server: https://kubernetes.default.svc
  - namespace: demo-gitops-cicd-dev
    server: https://kubernetes.default.svc
  - namespace: demo-gitops-cicd-stage
    server: https://kubernetes.default.svc
  - namespace: demo-gitops-cicd-prod
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
