---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app-editors
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: example-app
- apiGroup: user.openshift.io/v1
  kind: Group
  name: example-app-developers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app-admins
roleRef:
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: example-app-admins
