apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupConfig
metadata:
  name: tenant-config
spec:
  labelSelector:
    matchLabels:
      type: tenant
  templates:
  # cicd - admin
  - objectTemplate: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ splitList "-" .Name | initial | join "-" }}-cicd
        labels:
          tenant: {{ splitList "-" .Name | initial | join "-" }}
          type: cicd

  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: {{ .Name }}
        namespace: {{ splitList "-" .Name | initial | join "-" }}-cicd
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
      - kind: Group
        name: {{ .Name }}

  # dev - admin
  - objectTemplate: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ splitList "-" .Name | initial | join "-" }}-dev
        labels:
          tenant: {{ splitList "-" .Name | initial | join "-" }}
          type: runtime
          environment: dev

  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: {{ .Name }}
        namespace: {{ splitList "-" .Name | initial | join "-" }}-dev
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
      - kind: Group
        name: {{ .Name }}

    # qa - edit
  - objectTemplate: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ splitList "-" .Name | initial | join "-" }}-qa
        labels:
          tenant: {{ splitList "-" .Name | initial | join "-" }}
          type: runtime
          environment: qa

  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: {{ .Name }}
        namespace: {{ splitList "-" .Name | initial | join "-" }}-qa
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: Group
        name: {{ .Name }}

    # prod - edit
  - objectTemplate: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ splitList "-" .Name | initial | join "-" }}-prod
        labels:
          tenant: {{ splitList "-" .Name | initial | join "-" }}
          type: runtime
          environment: prod

  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: {{ .Name }}
        namespace: {{ splitList "-" .Name | initial | join "-" }}-prod
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: Group
        name: {{ .Name }}
